# Generated by Django 3.1.6 on 2021-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_url', models.CharField(max_length=1000)),
                ('shortened', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
